name: cmas
version: 0.0.2
description: cmas
author: yamal lng
homepage: http://yamallng.ru/

# Pubspec Format:
# https://www.dartlang.org/tools/pub/pubspec
#
# Repository of packages of software for the Dart programming language:
# https://pub.dartlang.org/

dependencies:
    angular2: ^3.0.0                      # Dart implementation of the Angular web framework. https://pub.dartlang.org/packages/angular2
    browser: ^0.10.0                      # The bootstrap dart.js script for Dart apps running in the browser. https://pub.dartlang.org/packages/browser
    dart_to_js_script_rewriter: ^1.0.2    # Replaces Dart script tags with JavaScript script tags. https://pub.dartlang.org/packages/dart_to_js_script_rewriter
    reflectable: ^1.0.2                   # Allows programmers to reduce certain usages of dynamic reflection to a transformer generated specialization with the same behavior. https://pub.dartlang.org/packages/reflectable
    alert:
      git: http://cm-ylng-msk-04/git/alert.frontend.git
    auth_router_outlet:
      git: http://cm-ylng-msk-04/git/auth_router_outlet.frontend.git
    bower_installer:
      git: http://cm-ylng-msk-04/git/bower_installer.frontend.git
    contracts:
      git: http://cm-ylng-msk-04/git/contracts.frontend.git
    dashboard:
      git: http://cm-ylng-msk-04/git/dashboard.frontend.git
    requests:
      git: http://cm-ylng-msk-04/git/requests.frontend.git
    object_budget_list:
      git: http://cm-ylng-msk-04/git/object_budget_list.frontend.git
    payment_budget_list:
      git: http://cm-ylng-msk-04/git/payment_budget_list.frontend.git
    object_list:
      git: http://cm-ylng-msk-04/git/object_list.frontend.git
    contractor_list:
      git: http://cm-ylng-msk-04/git/contractor_list.frontend.git
    resources_loader:
      git: http://cm-ylng-msk-04/git/resources_loader.frontend.git
    analytics:
      git: http://cm-ylng-msk-04/git/analytics.frontend.git
    object_budget:
       git: http://cm-ylng-msk-04/git/object_budget.frontend.git
    master_layout:
      git: http://cm-ylng-msk-04/git/master_layout.frontend.git
    logger:
      git: http://cm-ylng-msk-04/git/logger.frontend.git
    aside:
      git: http://cm-ylng-msk-04/git/aside.frontend.git
    config:
      git: http://cm-ylng-msk-04/git/config.frontend.git
    http_wrapper:
      git: http://cm-ylng-msk-04/git/http_wrapper.frontend.git
dev_dependencies:
    test: ^0.12.18                        # A library for writing dart unit tests. https://pub.dartlang.org/packages/test
    yaml: ^2.1.12                         # A parser for YAML. https://pub.dartlang.org/packages/yaml

#dependency_overrides:

# Used to configure dart2js or other transformers
transformers:
    - angular2:
        platform_directives:
          - package:angular2/common.dart#COMMON_DIRECTIVES
        platform_pipes:
          - package:angular2/common.dart#COMMON_PIPES
        entry_points: web/main.dart
        resolved_identifiers:
            BrowserClient: 'package:http/browser_client.dart'
            Client: 'package:http/http.dart'
    - reflectable:
        entry_points:
          - web/main.dart # The path to your main file
        formatted: true # Optional.
    - dart_to_js_script_rewriter
    - $dart2js:
        commandLineOptions:
            - --trust-type-annotations  # http://dovdev.com/get-the-most-out-of-dart2js-with-a-little-trust/
            - --trust-primitives        # http://dovdev.com/get-the-most-out-of-dart2js-with-a-little-trust/
            - --show-package-warnings # Show warnings and hints generated from packages