name: cmas
version: 0.0.2
description: cmas
author: yamal lng
homepage: http://yamallng.ru/

# Pubspec Format:
# https://www.dartlang.org/tools/pub/pubspec
#
# Repository of packages of software for the Dart programming language:
# https://pub.dartlang.org/

dependencies:
    angular2: ^2.2.0                      # Dart implementation of the Angular web framework. https://pub.dartlang.org/packages/angular2
    browser: ^0.10.0+2                    # The bootstrap dart.js script for Dart apps running in the browser. https://pub.dartlang.org/packages/browser
    dart_to_js_script_rewriter: ^1.0.2    # Replaces Dart script tags with JavaScript script tags. https://pub.dartlang.org/packages/dart_to_js_script_rewriter
    alert:
      #git: https://github.com/luckydimdim/alert.frontend.git
      git: http://cm-ylng-msk-04/git/alert.frontend.git
    auth_router_outlet:
      #git: https://github.com/luckydimdim/auth_router_outlet.frontend.git
      git: http://cm-ylng-msk-04/git/auth_router_outlet.frontend.git
    resources_loader:
      #git: https://github.com/luckydimdim/resources_loader.frontend.git
      git: http://cm-ylng-msk-04/git/resources_loader.frontend.git
    bower_installer:
      #git: https://github.com/luckydimdim/bower_installer.frontend.git
      git: http://cm-ylng-msk-04/git/bower_installer.frontend.git
    contract:
      #git: https://github.com/luckydimdim/contract.frontend.git
      git: http://cm-ylng-msk-04/git/contract.frontend.git
    contract_list:
      #git: https://github.com/luckydimdim/contract_list.frontend.git
      git: http://cm-ylng-msk-04/git/contract_list.frontend.git
    dashboard:
      #git: https://github.com/luckydimdim/dashboard.frontend.git
      git: http://cm-ylng-msk-04/git/dashboard.frontend.git
    auth_router_outlet:
      #git: https://github.com/luckydimdim/auth_router_outlet.frontend.git
      git: http://cm-ylng-msk-04/git/auth_router_outlet.frontend.git
    request_list:
      #git: https://github.com/luckydimdim/request_list.frontend.git
      git: http://cm-ylng-msk-04/git/request_list.frontend.git
    request:
      #git: https://github.com/luckydimdim/request.frontend.git
      git: http://cm-ylng-msk-04/git/request.frontend.git
    object_budget_list:
      #git: https://github.com/luckydimdim/object_budget_list.frontend.git
      git: http://cm-ylng-msk-04/git/object_budget_list.frontend.git
    payment_budget_list:
      #git: https://github.com/luckydimdim/payment_budget_list.frontend.git
      git: http://cm-ylng-msk-04/git/payment_budget_list.frontend.git
    object_list:
      #git: https://github.com/luckydimdim/object_list.frontend.git
      git: http://cm-ylng-msk-04/git/object_list.frontend.git
    contractor_list:
      #git: https://github.com/luckydimdim/contractor_list.frontend.git
      git: http://cm-ylng-msk-04/git/contractor_list.frontend.git
    resources_loader:
      #git: https://github.com/luckydimdim/resources_loader.frontend.git
      git: http://cm-ylng-msk-04/git/resources_loader.frontend.git
    analytics:
      #git: https://github.com/luckydimdim/analytics.frontend.git
      git: http://cm-ylng-msk-04/git/analytics.frontend.git
    object_budget:
       git: http://cm-ylng-msk-04/git/object_budget.frontend.git
    bower_installer:
      #git: https://github.com/luckydimdim/bower_installer.frontend.git
      git: http://cm-ylng-msk-04/git/bower_installer.frontend.git
    bambarbiya:
      path: lib/src/bambarbiya
dev_dependencies:
    test: ^0.12.18                        # A library for writing dart unit tests. https://pub.dartlang.org/packages/test
    yaml: ^2.1.12                         # A parser for YAML. https://pub.dartlang.org/packages/yaml      


# Used to configure dart2js or other transformers
transformers:
    - bower_installer
    - angular2:
        platform_directives:
          - package:angular2/common.dart#COMMON_DIRECTIVES
        platform_pipes:
          - package:angular2/common.dart#COMMON_PIPES
        entry_points: web/main.dart
    - dart_to_js_script_rewriter
    - $dart2js:
        commandLineOptions:
            - --trust-type-annotations
            - --trust-primitives
            - --show-package-warnings # Show warnings and hints generated from packages.
            - --enable-experimental-mirrors