# Mode
production: false

# Minimal log level
log_level: error

# Backend url
backend_scheme: http               # Scheme
backend_base_url: 'cm-ylng-msk-01' # Base service url
backend_port: '80'                 # Backend port

# API urls
backend_contracts: 'cmas-backend/contracts'
backend_logs: log
backend_call_off_orders: 'cmas-backend/call-off-orders'